/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proje;

import java.io.IOException;
import javax.swing.ButtonGroup;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author AYTAC
 */
public class ProjeForm extends javax.swing.JFrame {

    ButtonGroup dilSeçimiButtonGroup;
    Dil[] diller;

    public ProjeForm() {
        initComponents();
        dilSeçimiButtonGroup = new ButtonGroup();
        dilSeçimiButtonGroup.add(türkçeRadioButton);
        dilSeçimiButtonGroup.add(ingilizceRadioButton);
        dilSeçimiButtonGroup.add(ispanyolcaRadioButton);
        diller = new Dil[3];
        türkçeRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        URLTextArea = new javax.swing.JTextArea();
        tamamButton = new javax.swing.JButton();
        türkçeRadioButton = new javax.swing.JRadioButton();
        ingilizceRadioButton = new javax.swing.JRadioButton();
        ispanyolcaRadioButton = new javax.swing.JRadioButton();
        bağlantıAlLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        metinTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        kontrolEtButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sonuçTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        URLTextArea.setColumns(20);
        URLTextArea.setRows(5);
        jScrollPane1.setViewportView(URLTextArea);

        tamamButton.setText("Tamam");
        tamamButton.setName("tamamButton"); // NOI18N
        tamamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamamButtonActionPerformed(evt);
            }
        });

        türkçeRadioButton.setText("Türkçe");
        türkçeRadioButton.setName("türkçeRadioButton"); // NOI18N

        ingilizceRadioButton.setText("İngilizce");
        ingilizceRadioButton.setName("türkçeRadioButton"); // NOI18N

        ispanyolcaRadioButton.setText("İspanyolca");
        ispanyolcaRadioButton.setName("türkçeRadioButton"); // NOI18N

        jLabel1.setText("10 tane Wiki URL'si gir:");

        metinTextArea.setColumns(20);
        metinTextArea.setRows(5);
        jScrollPane2.setViewportView(metinTextArea);

        jLabel2.setText("Dil kontrolü için Wiki URL'si veya metin gir:");

        kontrolEtButton.setText("Kontrol Et");
        kontrolEtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontrolEtButtonActionPerformed(evt);
            }
        });

        sonuçTextArea.setColumns(20);
        sonuçTextArea.setRows(5);
        sonuçTextArea.setEnabled(false);
        jScrollPane3.setViewportView(sonuçTextArea);
        sonuçTextArea.getAccessibleContext().setAccessibleName("");
        sonuçTextArea.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bağlantıAlLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tamamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(türkçeRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingilizceRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ispanyolcaRadioButton))))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kontrolEtButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(bağlantıAlLabel))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kontrolEtButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(türkçeRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ingilizceRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ispanyolcaRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tamamButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tamamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamamButtonActionPerformed
        String urlKullanıcıMetni = URLTextArea.getText();

        //URL AL VE PARÇALARINA AYIR
        int urlSayısı = 0;
        int index = 0;
        String url = "";
        String[] urller = new String[10];
        while (index < urlKullanıcıMetni.length()) {
            if ((urlKullanıcıMetni.charAt(index) != 10) && (urlKullanıcıMetni.charAt(index) != 32)) {
                while (index < urlKullanıcıMetni.length() && ((urlKullanıcıMetni.charAt(index) != 10) && (urlKullanıcıMetni.charAt(index) != 32))) {
                    url += urlKullanıcıMetni.charAt(index);
                    index++;
                }
                urller[urlSayısı] = url;
                urlSayısı++;
                if (urlSayısı > 10) {
                    sonuçTextArea.setText("10 tane URL olmalı!");
                    return;
                }

                url = "";
            } else {
                index++;
            }
        }
        if (urlSayısı < 10) {
            sonuçTextArea.setText("10 tane URL olmalı!");
            return;
        }

        //METİNLERİ İNDİR
        Document doc;
        String[] context = new String[10];

        for (int i = 0; i < 10; i++) {
            try {
                doc = Jsoup.connect(urller[i]).get();
                context[i] = doc.select("div#mw-content-text").text();
            } catch (IOException e) {
                sonuçTextArea.setText("Hatalı URL");
                return;
            }
        }

        //METİNLERİ PARÇALA VE SIK KULLANILAN LİSTELERİNİ OLUŞTUR
        DilFactory fabrika = DilFactory.dilFactoryAl();

        if (türkçeRadioButton.isSelected()) {
            diller[0] = fabrika.dilAl(context);
        } else if (ingilizceRadioButton.isSelected()) {
            diller[1] = fabrika.dilAl(context);
        } else {
            diller[2] = fabrika.dilAl(context);
        }
    }//GEN-LAST:event_tamamButtonActionPerformed

    private void kontrolEtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontrolEtButtonActionPerformed
        //URL/METİN KONTROLÜ
        String kontrol = metinTextArea.getText();
        if (kontrol.equals("")) {
            return;
        }

        String metin;

        if (kontrol.subSequence(0, 4).equals("http")) {

            Document doc;

            try {
                doc = Jsoup.connect(kontrol).get();
                metin = doc.select("div#mw-content-text").text();
            } catch (IOException e) {
                sonuçTextArea.setText("Hatalı URL");
                return;
            }
        } else {
            metin = kontrol;
        }

        DilFactory fabrika = DilFactory.dilFactoryAl();
        //METİNDE TRİGRAMLARI VE KELİMELERİ ARA
        //KELİME

        Kelime[] kelimeler = fabrika.kelimelerineAyırv2(metin);

        //TRİGRAM
        //TRİGRAM KONTROL
        TriGram[] triGramlar = fabrika.triGramlarınaAyırv2(metin);

        //FİNAL-KOSİNÜS BENZERLİĞİ
        float[][] benzerlikOranları = new float[3][2];
        String sonuç = "";
        for (int i = 0; i < 3; i++) {
            if (diller[i] != null) {
                benzerlikOranları[i][0] = KosinüsBenzerliği.benzerlikHesaplaKelime(diller[i].getKelimeler(), kelimeler);
                benzerlikOranları[i][1] = KosinüsBenzerliği.benzerlikHesaplaTriGram(diller[i].getTriGramlar(), triGramlar);
                sonuç += "" + benzerlikOranları[i][0] + "/" + benzerlikOranları[i][1] + "||";
            }
        }

        sonuçTextArea.setText(sonuç);
    }//GEN-LAST:event_kontrolEtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea URLTextArea;
    private javax.swing.JLabel bağlantıAlLabel;
    private javax.swing.JRadioButton ingilizceRadioButton;
    private javax.swing.JRadioButton ispanyolcaRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kontrolEtButton;
    private javax.swing.JTextArea metinTextArea;
    private javax.swing.JTextArea sonuçTextArea;
    private javax.swing.JButton tamamButton;
    private javax.swing.JRadioButton türkçeRadioButton;
    // End of variables declaration//GEN-END:variables
}
